"""Remove assistant file id since it is the same as file id

Revision ID: 2cdf829ff4ac
Revises: 1f15098cb73a
Create Date: 2023-12-30 02:10:05.589746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cdf829ff4ac'
down_revision: Union[str, None] = '1f15098cb73a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'file_assistant_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('file_assistant_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
