"""Add Openai IDS to Well DB

Revision ID: 868343b24cb9
Revises: a66933f7d42a
Create Date: 2023-12-21 19:18:42.479777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '868343b24cb9'
down_revision: Union[str, None] = 'a66933f7d42a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('well', sa.Column('assistant_id', sa.String(), nullable=False))
    op.add_column('well', sa.Column('thread_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('well', 'thread_id')
    op.drop_column('well', 'assistant_id')
    # ### end Alembic commands ###
