"""add message id to message table

Revision ID: 9d911822088f
Revises: 2cdf829ff4ac
Create Date: 2024-01-02 10:53:27.296100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d911822088f'
down_revision: Union[str, None] = '2cdf829ff4ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('message_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'message_id')
    # ### end Alembic commands ###
