"""Add openai key to each well

Revision ID: e865e5a81bb3
Revises: 601e6844616d
Create Date: 2023-12-21 23:06:08.008758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e865e5a81bb3'
down_revision: Union[str, None] = '601e6844616d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('well', sa.Column('openai_api_key', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('well', 'openai_api_key')
    # ### end Alembic commands ###
